routes/admin.php
<?php

use App\Http\Controllers\Backend\AboutController;
use App\Http\Controllers\Backend\AddressController;
use App\Http\Controllers\Backend\AttributeController;
use App\Http\Controllers\Backend\AuthController;
use App\Http\Controllers\Backend\BrandController;
use App\Http\Controllers\Backend\CategoryController;
use App\Http\Controllers\Backend\ChatController;
use App\Http\Controllers\Backend\ColorController;
use App\Http\Controllers\Backend\CommissionController;
use App\Http\Controllers\Backend\CurrencyController;
use App\Http\Controllers\Backend\CustomerController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Backend\ErrorController;
use App\Http\Controllers\Backend\MemberShipController;
use App\Http\Controllers\Backend\MessageController;
use App\Http\Controllers\Backend\OrderController;
use App\Http\Controllers\Backend\PercentProductController;
use App\Http\Controllers\Backend\PolicyController;
use App\Http\Controllers\Backend\PosController;
use App\Http\Controllers\Backend\ProductController;
use App\Http\Controllers\Backend\ProfileController;
use App\Http\Controllers\Backend\RoleController;
use App\Http\Controllers\Backend\RuleController;
use App\Http\Controllers\Backend\SaleController;
use App\Http\Controllers\Backend\SellerController;
use App\Http\Controllers\Backend\StaffController;
use App\Http\Controllers\Backend\TaxController;
use App\Http\Controllers\Backend\UploadController;
use App\Http\Controllers\Backend\UserController;
use App\Http\Controllers\Backend\WithdrawRequestController;
use Illuminate\Support\Facades\Route;

use Illuminate\Events\Message;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('admin/', function () {
    return view('backend.dashboard');
});

Route::post('/send-message', function(Request $request){
    event(
        new Message(
            $request->input('username'),
            $request->input('message'))
    );
    return ["Succes"=>true];
});
    

// Route::get('auth/login', [AuthController::class, 'index'])->name('login');
// Route::post('/custom-signin', [AuthController::class, 'createSignin'])->name('signin.custom');

// Route::get('auth/register', [AuthController::class, 'register'])->name('register');
// Route::post('/create-user', [AuthController::class, 'customSignup'])->name('user.registration');

// Route::get('/dashboard', [AuthController::class, 'dashboardView'])->name('dashboard');
// Route::get('/logout', [AuthController::class, 'logout'])->name('logout');

// route product
Route::get('product', [ProductController::class, 'index'])->name('product');
Route::get('product/store', [ProductController::class, 'store'])->name('product.store');
Route::post('add/product', [ProductController::class, 'store'])->name('add/product');
Route::post('product/update/', [ProductController::class, 'update_product'])->name('product.update_product');
Route::get('all_product', [ProductController::class, 'allProuct'])->name('product_all');
Route::get('all_product_inhouse', [ProductController::class, 'allProuctInhouse'])->name('product_all_inhouse');
Route::get('all_product_seller', [ProductController::class, 'allProuctSeller'])->name('product_all_seller');
Route::post('product/sku_combination', [ProductController::class, 'sku_combination'])->name('products.sku_combination');
Route::post('product/sku_combination_edit', [ProductController::class, 'sku_combination_edit'])->name('products.sku_combination_edit');

// route category
Route::get('category', [CategoryController::class, 'index'])->name('get.category');
Route::get('add/category', [CategoryController::class, 'create'])->name('add.category');
Route::get('edit/category', [CategoryController::class, 'edit'])->name('edit.category');
Route::get('update/category', [CategoryController::class, 'update'])->name('update.category');
Route::get('delete/category', [CategoryController::class, 'destroy'])->name('delete.category');

// route brand
Route::resource('brand', BrandController::class);

Route::get('request_withdraw', [CustomerController::class, 'payoutRequest'])->name('customer_withdraw');

// route attribute
Route::resource('attribute', AttributeController::class);

// route color
Route::resource('color', ColorController::class);
Route::post('add/color', [ColorController::class, 'add_color'])->name('add.color');

Route::get('customer', [CustomerController::class, 'index'])->name('customer');
Route::get('payout', [CustomerController::class, 'payout'])->name('customer_payout');

Route::get('customer/index', [CustomerController::class, 'index'])->name('customer.index');
Route::get('payout', [CustomerController::class, 'payout'])->name('customer_payout');
Route::get('request_withdraw', [CustomerController::class, 'payoutRequest'])->name('customer_withdraw');
Route::get('status/{id}', [CustomerController::class, 'UpdateStatusUser'])->name('UpdateStatus');
Route::get('delete/customer/{id}', [CustomerController::class, 'destroy'])->name('delete/customer');
Route::put('update/customer/{id}', [CustomerController::class, 'update'])->name('update/customer');
Route::get('customer/memberfee', [CustomerController::class, 'membership'])->name('customer/memberfee');
Route::get('edit/customer/{id}', [CustomerController::class, 'edit'])->name('edit/customer');

Route::get('customer/refferid', [CustomerController::class, 'genkeyreffer'])->name('customer/refferid');
Route::post('add/customer/memberfee', [CustomerController::class, 'store'])->name('add/customer/memberfee');
Route::get('edit/customer/memberfee/{id}', [CustomerController::class, 'editMembership'])->name('edit/customer/memberfee');
Route::post('upate/customer/memberfee/{id}', [CustomerController::class, 'updateMembership'])->name('upate/customer/memberfee');

// route seller
Route::get('seller/index', [SellerController::class, 'index'])->name('seller.index');
Route::get('seller_commission', [SellerController::class, 'sellerCommission'])->name('seller_commission');
Route::get('seller_payout', [SellerController::class, 'sellerPayout'])->name('seller_payput');
Route::get('seller_withdraw', [SellerController::class, 'sellerWithdraw'])->name('seller_withdraw');
Route::put('update/seller/{id}', [SellerController::class, 'update'])->name('update/seller');
Route::get('edit/seller/{id}', [SellerController::class, 'edit'])->name('edit/seller');

// route employee
Route::resource('employee', StaffController::class);
Route::get('employee', [StaffController::class, 'index'])->name('employee');
Route::get('allemployee', [StaffController::class, 'allEmployee'])->name('all_employee');
Route::get('permission', [StaffController::class, 'permission'])->name('employee_permission');

Route::get('save/employee', [StaffController::class, 'store'])->name('manage.employee');

// rote order
Route::resource('sale', SaleController::class);
Route::get('sellerorder', [SaleController::class, 'sellerOrder'])->name('seller_order');
Route::get('inhouseorder', [SaleController::class, 'inHouseOrder'])->name('inhouse_order');
Route::get('detail/order', [SaleController::class, 'detailOrder'])->name('detail.order');

// route currency
Route::get('get/currency', [CurrencyController::class, 'index'])->name('get.currency');
Route::post('add/currency', [CurrencyController::class, 'store'])->name('add.currency');
Route::get('edit/{id}', [CurrencyController::class, 'edit'])->name('edit.currency');
Route::put('update/{id}', [CurrencyController::class, 'update'])->name('update.currency');
Route::delete('delete/{id}', [CurrencyController::class, 'destroy'])->name('delete.currency');
Route::get('status', [CurrencyController::class, 'submitDefault'])->name('defaultSubmit');

// route exchange
Route::get('exchange', [CurrencyController::class, 'exchangerate'])->name('exchangerate');
Route::post('add/exchange', [CurrencyController::class, 'insertexchangerate'])->name('add.exchangerate');
Route::get('edit/exchange/{id}', [CurrencyController::class, 'editexchangerate'])->name('edit.exchangerate');
Route::put('exchange/update/{id}', [CurrencyController::class, 'updateExchangerate'])->name('update.exchangerate');
Route::delete('delete/exchange/{id}', [CurrencyController::class, 'delete'])->name('delete.exchangerate');

// route rule
Route::get('rule', [RuleController::class, 'index'])->name('rule');

// route tax
Route::resource('tax', TaxController::class);
Route::get('tax', [TaxController::class, 'index'])->name('tax');
Route::get('status/tax', [TaxController::class, 'UpdateStatusNoti'])->name('UpdateStatusNoti');

// route message
Route::get('show/message', [MessageController::class, 'index'])->name('show.message');
Route::post('add/message', [MessageController::class, 'store'])->name('add.message');
Route::get('edit/message/{id}', [MessageController::class, 'edit'])->name('edit.message');
Route::put('update/message/{id}', [MessageController::class, 'update'])->name('update.message');
Route::delete('delete/message/{id}', [MessageController::class, 'destroy'])->name('delete.message');
Route::get('all_message', [MessageController::class, 'allMessage'])->name('all.message');
Route::get('seller_message', [MessageController::class, 'sellerMessage'])->name('seller.message');

// update message status
Route::get('update/status', [MessageController::class, 'UpdateStatusNoti'])->name('UpdateStatusNoti');

// route chat
Route::get('chat', [ChatController::class, 'index'])->name('chat');




//route upload file
Route::get('upload/file', [UploadController::class, 'index'])->name('upload/file');
Route::delete('delete/file/{id}', [UploadController::class, 'destroy'])->name('delete/file');

// route about

routes/web.php
<?php
use App\Http\Middleware\CheckLogin;

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\POSController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\MemberController;
use App\Http\Controllers\PaypalController;
use App\Http\Controllers\StripeController;
use App\Http\Controllers\UploadController;
use App\Http\Controllers\AccountController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\MywalletController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\Frontend\ShopController;
use App\Http\Controllers\Backend\AddressController;
use App\Http\Controllers\backend\CurrencyController;
use App\Http\Controllers\frontend\MessageController;
use App\Http\Controllers\frontend\ProductController;
use App\Http\Controllers\Frontend\ProductReciveController;
use App\Http\Controllers\Backend\WithdrawRequestController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', [HomeController::class, 'index'])->name('index');
Route::get('product_detail/{id}', [HomeController::class, 'product_detail'])->name('product_detail');
Route::get('product/seller/location/{id}', [ShopController::class, 'location'])->name('seller.location');

Route::get('products', [HomeController::class, 'product'])->name('shopping');
Route::get('cart', [HomeController::class, 'cart'])->name('cart');
Route::get('contact', [HomeController::class, 'contact'])->name('contact');
Route::get('product/category/{cat_id}', [ProductController::class, 'category'])->name('product.category');
Route::get('product/brand/{brand_id}', [ProductController::class, 'brand'])->name('product.brand');
Route::get('product/search', [ProductController::class, 'product_search'])->name('product_search');

Route::middleware([CheckLogin::class])->group(function () {
    // product route
    Route::get('account', [HomeController::class, 'account'])->name('account');
    Route::get('saller/dashboard', [HomeController::class, 'dashboard'])->name('saller.dashboard');
    // Route::resource('sale/product', \App\Http\Controllers\frontend\ProductController::class, ['as' => 'sale']);
    Route::get('sale/product', [ProductController::class, 'index'])->name('sale.product.index');
    Route::get('sale/product/create', [ProductController::class, 'create'])->name('sale.product.create');
    Route::get('sale/product/edit/{id}', [ProductController::class, 'edit'])->name('sale.product.edit');
    Route::get('sale/product/destroy/{id}', [\App\Http\Controllers\Backend\ProductController::class, 'destroy'])->name('sale.product.destroy');

    Route::post('seller/product/update', [ProductController::class, 'update_product'])->name('seller.update_product');
    Route::post('upload', [UploadController::class, 'upload'])->name('upload');
    Route::get('saller/product/search', [ProductController::class, 'search'])->name('saller.product.search');
    Route::get('saller/bestsell', [ProductController::class, 'bestsell'])->name('sale.bestsell');
    Route::get('saller/bestsell/search', [ProductController::class, 'bastSaleProduct'])->name('bast.search');

    // product recive route
    Route::get('/product/recive', [ProductReciveController::class, 'index'])->name('sale.product_recive');
    Route::get('/product/recive/create', [ProductReciveController::class, 'create'])->name('product_recive.create');
    Route::get('/product/recive/edit/{id}', [ProductReciveController::class, 'edit'])->name('product_recive.edit');
    Route::put('/product/recive/update/{id}', [ProductReciveController::class, 'update'])->name('product_recive.update');
    Route::get('/product/product_id', [ProductReciveController::class, 'variantion'])->name('variantion');
    Route::post('/product/recive/store', [ProductReciveController::class, 'store'])->name('producRecive.store');

    // order route
    Route::post('order/store', [OrderController::class, 'store'])->name('order.store');
    Route::get('order/confirmed', [CheckoutController::class, 'order_confirmed'])->name('order_confirmed');
    Route::get('order/all_order', [OrderController::class, 'all_order'])->name('order.all_order');
    Route::get('order/order_detail/{order_id}', [OrderController::class, 'order_detail'])->name('order.order_detail');
    Route::get('order/update_payment_status/{id}', [OrderController::class, 'update_payment_status'])->name('orders.update_payment_status');
    Route::post('order/update_delivery_status', [OrderController::class, 'update_delivery_status'])->name('orders.update_delivery_status');
    Route::get('customer/order', [OrderController::class, 'customer_order'])->name('customer.order');
    Route::get('customer/order_detail/{order_id}', [OrderController::class, 'customer_order_detail']);
    Route::get('order/search', [OrderController::class, 'search'])->name('order.search');
    Route::get('customer/order/search', [OrderController::class, 'customerSearch'])->name('purchase.search.order');
    Route::get('order/search/date', [OrderController::class, 'date'])->name('search.date');

    //sale route
    Route::get('/user/sale', [OrderController::class, 'saleAll'])->name('sale.all');
    Route::get('sale/sale_detail/{order_id}', [OrderController::class, 'sale_detail']);
    Route::get('/user/sale/date', [OrderController::class, 'saleDate'])->name('sale.search.date');

    // manage account route
    Route::post('account/update', [AccountController::class, 'update'])->name('account.update');
    Route::post('account/update_profile', [AccountController::class, 'update_profile'])->name('user.update_profile');
    Route::post('account/update_name', [AccountController::class, 'update_name'])->name('user.update_name');
    Route::post('account/update_email', [AccountController::class, 'update_email'])->name('user.update_email');
    Route::post('account/update_phone', [AccountController::class, 'update_phone'])->name('user.update_phone');
    Route::post('account/update_payment', [Accountcontroller::class, 'update_payment'])->name('user.update_payment');

    // shop setting
    Route::get('shop/setting', [ShopController::class, 'setting'])->name('shop.setting');
    Route::post('shop/store', [ShopController::class, 'store'])->name('shop.store');
    Route::post('shop/update', [ShopController::class, 'update'])->name('shop.update');

    // message routing
    Route::get('message/index', [MessageController::class, 'index'])->name('message');
    Route::get('sent/message', [MessageController::class, 'message'])->name('sent.message');
    Route::post('message/store', [MessageController::class, 'store'])->name('saller.message.store');

    Route::get('payment/history', [PaymentController::class, 'history'])->name('payment.history');
    Route::get('my/wallet', [MywalletController::class, 'wallet'])->name('my.wallet');

    // pos route
    Route::get('pos/index', [POSController::class, 'index'])->name('pos.index');
    Route::get('pos/add_to_cart/{id}', [POSController::class, 'add_to_cart'])->name('pos.add_to_cart');
    Route::post('pos/update_cart', [POSController::class, 'update_cart'])->name('pos.update_cart');
    Route::get('pos/remove_cart/{key}', [POSController::class, 'remove_cart'])->name('pos.remove_cart');
    Route::get('/pos/search_id/{value}', [POSController::class, 'search_id']);
    Route::get('pos/search_name', [POSController::class, 'search'])->name('pos.search');
    Route::get('pos/category/{id}', [POSController::class, 'category']);
    Route::get('pos/select/user_id', [POSController::class, 'select_user_id'])->name('select.user_id');
    Route::post('pos/checkout', [POSController::class, 'checkout'])->name('pos.checkout');
    Route::post('pos/credit-card', [POSController::class, 'credit_card'])->name('pos.credit-card');
    Route::get('pos/comfirm', [POSController::class, 'pos_order_confirmed'])->name('pos_order_confirmed');

    // members
    Route::get('member/level1', [MemberController::class, 'index'])->name('member.index');
    Route::get('member/all', [MemberController::class, 'all'])->name('member.all');
    Route::get('member/view/{id}', [MemberController::class, 'view'])->name('member.view');
    Route::get('member/view2/{id}', [MemberController::class, 'level2'])->name('member.view2');
    Route::get('member/view3/{id}', [MemberController::class, 'level3'])->name('member.view3');
    Route::get('member/shop', [MemberController::class, 'shop'])->name('member.shop');

    // address
    Route::get('change/address', [AddressController::class, 'change'])->name('change');
    Route::get('select/address/{id}', [AddressController::class, 'select'])->name('select.address');
    Route::get('address/edit', [AddressController::class, 'edit'])->name('edit.address');
    Route::post('address/update', [AddressController::class, 'address_update'])->name('update.address');

    Route::get('moneywithdraw', [WithdrawRequestController::class, 'moneywithdraw'])->name('moneywithdraw');
    
});

// route register and login and logout
Route::get('registration/{user_type}', [HomeController::class, 'registration'])->name('registration');
Route::post('register', [RegisterController::class, 'register'])->name('user.register');
Route::post('register/store', [RegisterController::class, 'store'])->name('user.register.store');
Route::get('sign-in', [HomeController::class, 'sign_in'])->name('sign_in');
Route::post('login', [HomeController::class, 'login'])->name('user.login');
Route::post('login/buy', [HomeController::class, 'login_buy'])->name('user.buy.login');

resources/views/backend/products/brand/create.blade.php
@extends('backend.layouts.sidebar')
@section('content')
 <!-- BEGIN: Content -->
        <div class="content">
        <div class="intro-y flex items-center mt-8">
            <h2 class="text-lg font-medium mr-auto text-xl">
                Add New Brand
            </h2>
        </div>
        <div class="grid grid-cols-6 gap-12 mt-5">
                <form action="{{route('brand.store')}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="intro-y box">
                        <div id="vertical-form" class="p-5">
                            <div class="preview">
                                <div>
                                    <label for="vertical-form-1" class="form-label text-base">Name</label>
                                    <input id="vertical-form-1" type="text" class="form-control border-gray-500 text-base" name="name" placeholder="Name" required>
                                    @error('name')
                                    <span style="color: red;">{{ $message }}</span>
                                    @enderror
                                </div>
                                <div>
                                    <label for="vertical-form-1" class="form-label">Logo</label>
                                    <input id="vertical-form-1" type="file" class="form-control cursor-pointer border-gray-500" name="logo" >
                                </div>
                                <div>
                                    <label for="vertical-form-1" class="form-label text-base">Slug</label>
                                    <input id="vertical-form-1" type="text" class="form-control border-gray-500" name="slug" placeholder="Slug">
                                </div>
                                <div>
                                    <label for="vertical-form-1" class="form-label text-base">Meta Title</label>
                                    <input id="vertical-form-1" type="text" class="form-control border-gray-500" name="meta_title" placeholder="Meta Title">
                                </div>
                                <div>
                                    <label for="vertical-form-1" class="form-label text-base">Meta Description</label>
                                    <textarea type="text" class="form-control border-gray-500" name="meta_descriiption" placeholder="Meta Description" rows="4" cols="50"></textarea>
                                </div>
                                <div>
                                    <button type="submit" class="btn btn-primary mt-5 text-base">Save</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
<!-- END: Content -->
    
@endsection

resources/views/backend/products/brand/edit.blade.php
@extends('backend.layouts.sidebar')
@section('content')
 <!-- BEGIN: Content -->
    <div class="content">
    <div class="intro-y flex items-center mt-8">
        <h2 class="text-lg font-medium mr-auto text-xl">
            Edit Brand
        </h2>
    </div>
    <div class="grid grid-cols-6 gap-12 mt-5">
        <div class="intro-y col-span-12 lg:col-span-6">
            <form action="{{route('brand.update', $brand->id)}}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="intro-y box">
                    <div id="vertical-form" class="p-5">
                        <div class="preview">
                            <div>
                                <label for="vertical-form-1" class="form-label text-base">Name</label>
                                <input id="vertical-form-1" type="text" class="form-control border-gray-500 text-base" name="name" value="{{$brand->name}}" placeholder="Brand Name" required>
                                @error('name')
                                <span style="color: red;">{{ $message }}</span>
                                @enderror
                            </div>
                            <div>
                                <strong>Logo</strong>
                                <input type="file" name="logo" class="form-control" placeholder="Logo">
                                <img src="/uploads/images/{{ $brand->logo }}" width="150px">
                            </div>
                            <div>
                                <label for="vertical-form-1" class="form-label text-base">Slug</label>
                                <input id="vertical-form-1" type="text" class="form-control border-gray-500 text-base" name="slug" value="{{$brand->slug}}" placeholder="Slug">
                            </div>
                            <div>
                                <label for="vertical-form-1" class="form-label text-base">Meta Title</label>
                                <input id="vertical-form-1" type="text" class="form-control border-gray-500 text-base" name="meta_title" value="{{$brand->meta_title}}" placeholder="Meta Title">
                            </div>
                            <div>
                                <label for="vertical-form-1" class="form-label text-base">Meta Description</label>
                                <textarea id="vertical-form-1" type="text" name="meta_description" class="form-control border-gray-500 text-base" placeholder="meta_description" rows="4" cols="50">{{$brand->meta_description}}</textarea>
                            </div>
                            <div>
                                <button type="submit" class="btn btn-primary mt-5 text-base">Edit</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- END: Content -->
    
@endsection

resources/views/backend/products/brand/index.blade.php
@extends('backend.layouts.sidebar')
@section('content')
 
 <!-- BEGIN: Content -->
    <div class="content">
        <h2 class="intro-y text-lg font-medium mt-10 text-xl">
            All Brand
        </h2>
        <div class="grid grid-cols-12 gap-6 mt-5"> 
            <div class="intro-y col-span-12 flex flex-wrap sm:flex-nowrap items-center mt-2">
                <a href="{{route('brand.create')}}" class="btn btn-primary shadow-md mr-2 text-base">Add New Brand</a>
                <div class="hidden md:block mx-auto text-gray-600"></div>
               
            </div>
            <!-- BEGIN: Data List -->
            <div class="intro-y col-span-12 overflow-auto lg:overflow-visible">
                <table class="table table-report -mt-2" id="dataTable">
                    <thead>
                        <tr>
                            <th class="whitespace-nowrap text-base">#</th>
                            <th class="whitespace-nowrap text-base">NAME</th>
                            <th class="whitespace-nowrap text-base">LOGO</th>
                            <th class="whitespace-nowrap text-base">META TITLE</th>
                            <th class="text-center whitespace-nowrap text-base">ACTIONS</th>
                        </tr>
                    </thead>
                    <tbody>
                        @php
                            $i = 0;
                        @endphp
                        @foreach ($brands as $brand)
                        <tr class="intro-x">
                            <td class="text-base">{{++$i}}</td>
                            <td class="text-base">{{$brand->name}}</td>
                            <td><img src="uploads/images/{{$brand->logo}}" style="max-width: 60px;max-height:60px" alt=""></td>
                            <td class="text-base">{{$brand->meta_title ?? ''}}</td>
                            <td class="table-report__action w-56 p-5">
                                <div class="flex justify-center items-center">
                                    <a class="btn btn-primary" href="{{route('brand.edit', $brand->id)}}"> <i data-feather="check-square" class="w-4 h-3 mr-1"></i></a>
                                    <form action="{{route('brand.destroy', $brand->id)}}" method="POST" class="px-2">
                                            @csrf
                                        @method('DELETE')
                                        {{-- <button class="flex items-center text-theme-24" data-toggle="modal" data-target="#delete-confirmation-modal"> <i data-feather="trash-2" class="w-4 h-4 mr-1"></i>Delete</button> --}}
                                        <button type="submit" class="btn btn-danger btn_delete"> <i data-feather="trash-2" class="w-4 h-3 mr-1"></i></button>
                                    </form>
                                    
                                </div>
                            </td>
                        </tr>
                            @endforeach
                    </tbody>
                </table>
            </div>
            <!-- END: Data List -->
        </div>
    </div>
    <!-- END: Content -->

    <script>
        $(document).ready(function() {
            $('#dataTable').DataTable();    
        });
    </script>
    
@endsection