routes/admin.php
<?php

use App\Http\Controllers\Backend\AboutController;
use App\Http\Controllers\Backend\AddressController;
use App\Http\Controllers\Backend\AttributeController;
use App\Http\Controllers\Backend\AuthController;
use App\Http\Controllers\Backend\BrandController;
use App\Http\Controllers\Backend\CategoryController;
use App\Http\Controllers\Backend\ChatController;
use App\Http\Controllers\Backend\ColorController;
use App\Http\Controllers\Backend\CommissionController;
use App\Http\Controllers\Backend\CurrencyController;
use App\Http\Controllers\Backend\CustomerController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Backend\ErrorController;
use App\Http\Controllers\Backend\MemberShipController;
use App\Http\Controllers\Backend\MessageController;
use App\Http\Controllers\Backend\OrderController;
use App\Http\Controllers\Backend\PercentProductController;
use App\Http\Controllers\Backend\PolicyController;
use App\Http\Controllers\Backend\PosController;
use App\Http\Controllers\Backend\ProductController;
use App\Http\Controllers\Backend\ProfileController;
use App\Http\Controllers\Backend\RoleController;
use App\Http\Controllers\Backend\RuleController;
use App\Http\Controllers\Backend\SaleController;
use App\Http\Controllers\Backend\SellerController;
use App\Http\Controllers\Backend\StaffController;
use App\Http\Controllers\Backend\TaxController;
use App\Http\Controllers\Backend\UploadController;
use App\Http\Controllers\Backend\UserController;
use App\Http\Controllers\Backend\WithdrawRequestController;
use Illuminate\Support\Facades\Route;

use Illuminate\Events\Message;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('admin/', function () {
    return view('backend.dashboard');
});

Route::post('/send-message', function(Request $request){
    event(
        new Message(
            $request->input('username'),
            $request->input('message'))
    );
    return ["Succes"=>true];
});
    

// Route::get('auth/login', [AuthController::class, 'index'])->name('login');
// Route::post('/custom-signin', [AuthController::class, 'createSignin'])->name('signin.custom');

// Route::get('auth/register', [AuthController::class, 'register'])->name('register');
// Route::post('/create-user', [AuthController::class, 'customSignup'])->name('user.registration');

// Route::get('/dashboard', [AuthController::class, 'dashboardView'])->name('dashboard');
// Route::get('/logout', [AuthController::class, 'logout'])->name('logout');

// route product
Route::get('product', [ProductController::class, 'index'])->name('product');
Route::get('product/store', [ProductController::class, 'store'])->name('product.store');
Route::post('add/product', [ProductController::class, 'store'])->name('add/product');
Route::post('product/update/', [ProductController::class, 'update_product'])->name('product.update_product');
Route::get('all_product', [ProductController::class, 'allProuct'])->name('product_all');
Route::get('all_product_inhouse', [ProductController::class, 'allProuctInhouse'])->name('product_all_inhouse');
Route::get('all_product_seller', [ProductController::class, 'allProuctSeller'])->name('product_all_seller');
Route::post('product/sku_combination', [ProductController::class, 'sku_combination'])->name('products.sku_combination');
Route::post('product/sku_combination_edit', [ProductController::class, 'sku_combination_edit'])->name('products.sku_combination_edit');

// route category
Route::get('category', [CategoryController::class, 'index'])->name('get.category');
Route::get('add/category', [CategoryController::class, 'create'])->name('add.category');
Route::get('edit/category', [CategoryController::class, 'edit'])->name('edit.category');
Route::get('update/category', [CategoryController::class, 'update'])->name('update.category');
Route::get('delete/category', [CategoryController::class, 'destroy'])->name('delete.category');

// route brand
Route::resource('brand', BrandController::class);

Route::get('request_withdraw', [CustomerController::class, 'payoutRequest'])->name('customer_withdraw');

// route attribute
Route::resource('attribute', AttributeController::class);

// route color
Route::resource('color', ColorController::class);
Route::post('add/color', [ColorController::class, 'add_color'])->name('add.color');

Route::get('customer', [CustomerController::class, 'index'])->name('customer');
Route::get('payout', [CustomerController::class, 'payout'])->name('customer_payout');

Route::get('customer/index', [CustomerController::class, 'index'])->name('customer.index');
Route::get('payout', [CustomerController::class, 'payout'])->name('customer_payout');
Route::get('request_withdraw', [CustomerController::class, 'payoutRequest'])->name('customer_withdraw');
Route::get('status/{id}', [CustomerController::class, 'UpdateStatusUser'])->name('UpdateStatus');
Route::get('delete/customer/{id}', [CustomerController::class, 'destroy'])->name('delete/customer');
Route::put('update/customer/{id}', [CustomerController::class, 'update'])->name('update/customer');
Route::get('customer/memberfee', [CustomerController::class, 'membership'])->name('customer/memberfee');
Route::get('edit/customer/{id}', [CustomerController::class, 'edit'])->name('edit/customer');

Route::get('customer/refferid', [CustomerController::class, 'genkeyreffer'])->name('customer/refferid');
Route::post('add/customer/memberfee', [CustomerController::class, 'store'])->name('add/customer/memberfee');
Route::get('edit/customer/memberfee/{id}', [CustomerController::class, 'editMembership'])->name('edit/customer/memberfee');
Route::post('upate/customer/memberfee/{id}', [CustomerController::class, 'updateMembership'])->name('upate/customer/memberfee');

// route seller
Route::get('seller/index', [SellerController::class, 'index'])->name('seller.index');
Route::get('seller_commission', [SellerController::class, 'sellerCommission'])->name('seller_commission');
Route::get('seller_payout', [SellerController::class, 'sellerPayout'])->name('seller_payput');
Route::get('seller_withdraw', [SellerController::class, 'sellerWithdraw'])->name('seller_withdraw');
Route::put('update/seller/{id}', [SellerController::class, 'update'])->name('update/seller');
Route::get('edit/seller/{id}', [SellerController::class, 'edit'])->name('edit/seller');

// route employee
Route::resource('employee', StaffController::class);
Route::get('employee', [StaffController::class, 'index'])->name('employee');
Route::get('allemployee', [StaffController::class, 'allEmployee'])->name('all_employee');
Route::get('permission', [StaffController::class, 'permission'])->name('employee_permission');

Route::get('save/employee', [StaffController::class, 'store'])->name('manage.employee');

// rote order
Route::resource('sale', SaleController::class);
Route::get('sellerorder', [SaleController::class, 'sellerOrder'])->name('seller_order');
Route::get('inhouseorder', [SaleController::class, 'inHouseOrder'])->name('inhouse_order');
Route::get('detail/order', [SaleController::class, 'detailOrder'])->name('detail.order');

// route currency
Route::get('get/currency', [CurrencyController::class, 'index'])->name('get.currency');
Route::post('add/currency', [CurrencyController::class, 'store'])->name('add.currency');
Route::get('edit/{id}', [CurrencyController::class, 'edit'])->name('edit.currency');
Route::put('update/{id}', [CurrencyController::class, 'update'])->name('update.currency');
Route::delete('delete/{id}', [CurrencyController::class, 'destroy'])->name('delete.currency');
Route::get('status', [CurrencyController::class, 'submitDefault'])->name('defaultSubmit');

// route exchange
Route::get('exchange', [CurrencyController::class, 'exchangerate'])->name('exchangerate');
Route::post('add/exchange', [CurrencyController::class, 'insertexchangerate'])->name('add.exchangerate');
Route::get('edit/exchange/{id}', [CurrencyController::class, 'editexchangerate'])->name('edit.exchangerate');
Route::put('exchange/update/{id}', [CurrencyController::class, 'updateExchangerate'])->name('update.exchangerate');
Route::delete('delete/exchange/{id}', [CurrencyController::class, 'delete'])->name('delete.exchangerate');

// route rule
Route::get('rule', [RuleController::class, 'index'])->name('rule');

// route tax
Route::resource('tax', TaxController::class);
Route::get('tax', [TaxController::class, 'index'])->name('tax');
Route::get('status/tax', [TaxController::class, 'UpdateStatusNoti'])->name('UpdateStatusNoti');

// route message
Route::get('show/message', [MessageController::class, 'index'])->name('show.message');
Route::post('add/message', [MessageController::class, 'store'])->name('add.message');
Route::get('edit/message/{id}', [MessageController::class, 'edit'])->name('edit.message');
Route::put('update/message/{id}', [MessageController::class, 'update'])->name('update.message');
Route::delete('delete/message/{id}', [MessageController::class, 'destroy'])->name('delete.message');
Route::get('all_message', [MessageController::class, 'allMessage'])->name('all.message');
Route::get('seller_message', [MessageController::class, 'sellerMessage'])->name('seller.message');

// update message status
Route::get('update/status', [MessageController::class, 'UpdateStatusNoti'])->name('UpdateStatusNoti');

// route chat
Route::get('chat', [ChatController::class, 'index'])->name('chat');




//route upload file
Route::get('upload/file', [UploadController::class, 'index'])->name('upload/file');
Route::delete('delete/file/{id}', [UploadController::class, 'destroy'])->name('delete/file');

// route about

routes/web.php
Route::get('product/category/{cat_id}', [ProductController::class, 'category'])->name('product.category');
Route::get('product/brand/{brand_id}', [ProductController::class, 'brand'])->name('product.brand');
Route::get('product/search', [ProductController::class, 'product_search'])->name('product_search');

Route::middleware([CheckLogin::class])->group(function () {
    // product route
    Route::get('account', [HomeController::class, 'account'])->name('account');
    Route::get('saller/dashboard', [HomeController::class, 'dashboard'])->name('saller.dashboard');
    // Route::resource('sale/product', \App\Http\Controllers\frontend\ProductController::class, ['as' => 'sale']);
    Route::get('sale/product', [ProductController::class, 'index'])->name('sale.product.index');
    Route::get('sale/product/create', [ProductController::class, 'create'])->name('sale.product.create');
    Route::get('sale/product/edit/{id}', [ProductController::class, 'edit'])->name('sale.product.edit');
    Route::get('sale/product/destroy/{id}', [\App\Http\Controllers\Backend\ProductController::class, 'destroy'])->name('sale.product.destroy');

    Route::post('seller/product/update', [ProductController::class, 'update_product'])->name('seller.update_product');
    Route::post('upload', [UploadController::class, 'upload'])->name('upload');
    Route::get('saller/product/search', [ProductController::class, 'search'])->name('saller.product.search');
    Route::get('saller/bestsell', [ProductController::class, 'bestsell'])->name('sale.bestsell');
    Route::get('saller/bestsell/search', [ProductController::class, 'bastSaleProduct'])->name('bast.search');

    // product recive route
    Route::get('/product/recive', [ProductReciveController::class, 'index'])->name('sale.product_recive');
    Route::get('/product/recive/create', [ProductReciveController::class, 'create'])->name('product_recive.create');
    Route::get('/product/recive/edit/{id}', [ProductReciveController::class, 'edit'])->name('product_recive.edit');
    Route::put('/product/recive/update/{id}', [ProductReciveController::class, 'update'])->name('product_recive.update');
    Route::get('/product/product_id', [ProductReciveController::class, 'variantion'])->name('variantion');
    Route::post('/product/recive/store', [ProductReciveController::class, 'store'])->name('producRecive.store');

    // order route
    Route::post('order/store', [OrderController::class, 'store'])->name('order.store');
    Route::get('order/confirmed', [CheckoutController::class, 'order_confirmed'])->name('order_confirmed');
    Route::get('order/all_order', [OrderController::class, 'all_order'])->name('order.all_order');
    Route::get('order/order_detail/{order_id}', [OrderController::class, 'order_detail'])->name('order.order_detail');
    Route::get('order/update_payment_status/{id}', [OrderController::class, 'update_payment_status'])->name('orders.update_payment_status');
    Route::post('order/update_delivery_status', [OrderController::class, 'update_delivery_status'])->name('orders.update_delivery_status');
    Route::get('customer/order', [OrderController::class, 'customer_order'])->name('customer.order');
    Route::get('customer/order_detail/{order_id}', [OrderController::class, 'customer_order_detail']);
    Route::get('order/search', [OrderController::class, 'search'])->name('order.search');
    Route::get('customer/order/search', [OrderController::class, 'customerSearch'])->name('purchase.search.order');
    Route::get('order/search/date', [OrderController::class, 'date'])->name('search.date');

    //sale route
    Route::get('/user/sale', [OrderController::class, 'saleAll'])->name('sale.all');
    Route::get('sale/sale_detail/{order_id}', [OrderController::class, 'sale_detail']);
    Route::get('/user/sale/date', [OrderController::class, 'saleDate'])->name('sale.search.date');

    // manage account route
    Route::post('account/update', [AccountController::class, 'update'])->name('account.update');
    Route::post('account/update_profile', [AccountController::class, 'update_profile'])->name('user.update_profile');
    Route::post('account/update_name', [AccountController::class, 'update_name'])->name('user.update_name');
    Route::post('account/update_email', [AccountController::class, 'update_email'])->name('user.update_email');
    Route::post('account/update_phone', [AccountController::class, 'update_phone'])->name('user.update_phone');
    Route::post('account/update_payment', [Accountcontroller::class, 'update_payment'])->name('user.update_payment');

    // shop setting
    Route::get('shop/setting', [ShopController::class, 'setting'])->name('shop.setting');
    Route::post('shop/store', [ShopController::class, 'store'])->name('shop.store');
    Route::post('shop/update', [ShopController::class, 'update'])->name('shop.update');

    // message routing
    Route::get('message/index', [MessageController::class, 'index'])->name('message');
    Route::get('sent/message', [MessageController::class, 'message'])->name('sent.message');
    Route::post('message/store', [MessageController::class, 'store'])->name('saller.message.store');

    Route::get('payment/history', [PaymentController::class, 'history'])->name('payment.history');
    Route::get('my/wallet', [MywalletController::class, 'wallet'])->name('my.wallet');

    // pos route
    Route::get('pos/index', [POSController::class, 'index'])->name('pos.index');
    Route::get('pos/add_to_cart/{id}', [POSController::class, 'add_to_cart'])->name('pos.add_to_cart');
    Route::post('pos/update_cart', [POSController::class, 'update_cart'])->name('pos.update_cart');
    Route::get('pos/remove_cart/{key}', [POSController::class, 'remove_cart'])->name('pos.remove_cart');
    Route::get('/pos/search_id/{value}', [POSController::class, 'search_id']);
    Route::get('pos/search_name', [POSController::class, 'search'])->name('pos.search');
    Route::get('pos/category/{id}', [POSController::class, 'category']);
    Route::get('pos/select/user_id', [POSController::class, 'select_user_id'])->name('select.user_id');
    Route::post('pos/checkout', [POSController::class, 'checkout'])->name('pos.checkout');
    Route::post('pos/credit-card', [POSController::class, 'credit_card'])->name('pos.credit-card');
    Route::get('pos/comfirm', [POSController::class, 'pos_order_confirmed'])->name('pos_order_confirmed');

    // members
    Route::get('member/level1', [MemberController::class, 'index'])->name('member.index');
    Route::get('member/all', [MemberController::class, 'all'])->name('member.all');
    Route::get('member/view/{id}', [MemberController::class, 'view'])->name('member.view');
    Route::get('member/view2/{id}', [MemberController::class, 'level2'])->name('member.view2');
    Route::get('member/view3/{id}', [MemberController::class, 'level3'])->name('member.view3');
    Route::get('member/shop', [MemberController::class, 'shop'])->name('member.shop');

    // address
    Route::get('change/address', [AddressController::class, 'change'])->name('change');
    Route::get('select/address/{id}', [AddressController::class, 'select'])->name('select.address');
    Route::get('address/edit', [AddressController::class, 'edit'])->name('edit.address');
    Route::post('address/update', [AddressController::class, 'address_update'])->name('update.address');

    Route::get('moneywithdraw', [WithdrawRequestController::class, 'moneywithdraw'])->name('moneywithdraw');
    
});

// route register and login and logout
Route::get('registration/{user_type}', [HomeController::class, 'registration'])->name('registration');
Route::post('register', [RegisterController::class, 'register'])->name('user.register');
Route::post('register/store', [RegisterController::class, 'store'])->name('user.register.store');
Route::get('sign-in', [HomeController::class, 'sign_in'])->name('sign_in');
Route::post('login', [HomeController::class, 'login'])->name('user.login');
Route::post('login/buy', [HomeController::class, 'login_buy'])->name('user.buy.login');
Route::get('/user/logout', [HomeController::class, 'logout'])->name('user.logout');

// cart route
Route::post('select-color', [CartController::class, 'select_color'])->name('choose');
Route::post('select/product', [CartController::class, 'select_product'])->name('select');
Route::post('add_to_cart', [CartController::class, 'add_to_cart'])->name('add_to_cart');
Route::get('cart_destroy', [CartController::class, 'cart_destroy'])->name('cart_destroy');
Route::get('cart_remove/{key}', [CartController::class, 'cart_remove'])->name('remove');
Route::post('update_cart', [CartController::class, 'update_cart'])->name('update_cart');



Route::post('/currency/change', [CurrencyController::class, 'changeCurrency'])->name('currency.change');


// Payment route/
// Route::get('stripe', [StripeController::class, 'stripe']);
// Route::post('stripe/payment', [StripeController::class, 'stripePost'])->name('stripe.post');
// Route::post('checkout', [StripeController::class, 'afterpayment'])->name('checkout.credit-card');

// paypal payment
Route::get('paypal/payment', [PaypalController::class, 'index'])->name('paypal.index');

// paypal route
Route::get('paypal', [PaypalController::class, 'index'])->name('paypal.index');
Route::get('success-paypal', [PayPalController::class, 'successPaypal'])->name('success.paypal');
Route::get('cancel-paypal', [PayPalController::class, 'cancelPaypal'])->name('cancel.paypal');

// checkout route
Route::get('checkout', [CheckoutController::class, 'checkout'])->name('checkout');
Route::get('shipping', [CheckoutController::class, 'shipping'])->name('shipping');
Route::get('checkout/delivery_info', [CheckoutController::class, 'delivery_info'])->name('delivery_info');
Route::get('checkout/payment_select/{owner_id}', [CheckoutController::class, 'store_delivery_info'])->name('checkout.store_delivery_info');
Route::post('checkout/payment', [CheckoutController::class, 'checkout'])->name('payment.checkout');

resources/views/backend/settings/tax/index.blade.php
@extends('backend.layouts.sidebar')
@section('content')
 <!-- BEGIN: Content -->
                
    <div class="content">
    <div class="intro-y flex items-center mt-8">
        <h1 class="text-xl font-medium mr-auto">
        All Taxes
        </h1>
    </div>
    <div class="grid grid-cols-12 gap-6 mt-5">
        <div class="intro-y col-span-12 overflow-auto">
            <div class="float-right">
                <a type="submit" class="btn btn-primary text-base" data-toggle="modal" data-target="#modal-add">Add New Tax</a>
            </div>
        <!-- insert -->
        <div class="intro-y box mt-5">
                <div id="header-footer-modal">
                    <div class="preview">
                        <div id="modal-add" class="modal" tabindex="-1" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h2 class="font-medium text-base mr-auto text-lg">
                                        Add New Tax
                                        </h2>
                                        <button type="button" data-dismiss="modal" class="col-span-6 sm:col-span-3 lg:col-span-2 xl:col-span-1"><i data-feather="x" class="block mx-auto"></i> </button>
                                        
                                    </div>
                                    <form action="{{route('tax.store')}}" method="POST">
                                        @csrf
                                        <div class="modal-body grid grid-cols-6 gap-4 gap-y-3">
                                            <div class="col-span-12 sm:col-span-6">
                                                <label for="modal-form-1" class="form-label text-base">Country Name</label>
                                                <input id="modal-form-1" type="text" name="name" class="form-control border-gray-500 text-base" placeholder="Country Name" required>
                                            </div>
                                            <div class="col-span-12 sm:col-span-6">
                                                <label for="modal-form-1" class="form-label text-base">Tax Price</label>
                                                <input id="modal-form-1" type="text" name="tax" class="form-control border-gray-500 text-base" placeholder="Tax price" required>
                                            </div>
                                        </div>
                                        <div class="modal-footer text-right">
                                            <button type="button" data-dismiss="modal" class="btn btn-danger w-20 mr-1 text-base">Cancel</button>
                                            <button type="submit" class="btn btn-primary w-20 text-base">Save</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        </div>

        <!-- end insert -->
            <table class="table table-report -mt-2" id="dataTable">
                <thead>
                    <tr>
                        <th class="whitespace-nowrap text-base">#</th>
                        <th class="whitespace-nowrap text-base">Country Name</th>
                        <th class="whitespace-nowrap text-base">Tax Price</th>
                        <th class="whitespace-nowrap text-base">Status</th>
                        <th class="whitespace-nowrap text-base">Switch</th>
                        <th class="text-center whitespace-nowrap text-base">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @php
                        $i = 0;
                    @endphp
                    @foreach ($tax as $item)
                    <tr class="intro-x">
                        <td class="w-40">{{++$i}}</td>
                        <td>{{ substr($item->name,0,80) }} ....</td>
                        <td>{{ $item->tax }} ....</td>
                        <td id="resp{{ $item->id }}">
                            <br>
                                @if($item->status == 1)
                                <button type="button" class="btn btn-sm btn-success text-base">Active</button>
                                    @else
                                <button type="button" class="btn btn-sm btn-danger text-base">Inactive</button>
                                @endif
                            </td>
                        <td>
                        <input data-id="{{ $item->id }}" class="form-check-switch" type="checkbox" data-onstyle="success" data-offstyle="danger" data-toggle="toggle" data-on="Active" data-off="InActive" {{ $item->status ? 'checked' : '' }}>
                        <span class="slider round"></span>
                        </td>
                        <td class="table-report__action w-56 p-5">
                            <div class="flex justify-center items-center">
                                <a class="btn btn-primary" href="">  <i class="w-4 h-3 mr-2" data-feather="eye"></i></a>
                                <form action="{{route('tax.destroy', $item->id)}}" method="POST" class="px-2">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger btn_delete"> <i data-feather="trash-2" class="w-4 h-3 mr-1"></i></button>
                                </form>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
    </div>

    </div>
</div>
<!-- END: Content -->
<script>
    $(document).ready(function() {
        $('#dataTable').DataTable();    
    });
</script>

        <script src="{{ asset('js/jquery.min.js') }}"></script>

        <script type="text/javascript">
            $(document).ready(function() {
                $(window).load(function() {
                    $(".cargando").fadeOut(1000);
                });


        $('.form-check-switch').change(function() {
            //Verifico el estado del checkbox, si esta seleccionado sera igual a 1 de lo contrario sera igual a 0
            var status = $(this).prop('checked') == true ? 1 : 0; 
            var id = $(this).data('id'); 
                console.log(status);

            $.ajax({
                type: "GET",
                dataType: "json",
                //url: '/StatusNoticia',
                url: '{{ route('UpdateStatusNoti') }}',
                data: {'status': status, 'id': id},
                success: function(data){
                    $('#resp' + id).html(data.var); 
                    console.log(data.var)
                
                }
            });
        })
            
        });
        </script>
    
@endsection